### ISSUE TITLE
Dashboard app requests extraneous GitHub permissions

### ISSUE THREAD

**Issue by peter-evans** [stryker-mutator/stryker-dashboard#95]
When logging into the app with GitHub the Stryker dashboard requests access to read and write to all public and private repositories of the user. This doesn't seem necessary.

As an example, [Coveralls](https://coveralls.io/), which is a somewhat similar type of app, requests the following permissions.
![image](https://user-images.githubusercontent.com/18365890/43691675-f65d4a38-995a-11e8-9cf3-c77b6732a72e.png)

This is a link to the documentation on scopes:
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes
The scope "repo:status" can be used to give the app access to the commit statuses. I think this will allow you to show the mutation score for each commit without needing full access to the code of user's repositories.

**Comment by ptoonen** [comment]
@nicojs judging on #96 this issue can be closed, can you confirm?

**Comment by ptoonen** [comment]
Hi @peter-evans the issue has been resolved a while ago with #96 
Thanks for reporting it, we must've missed this issue!

**Comment by peter-evans** [comment]
Has it been released yet? I'm still seeing the dashboard request full access to my private repositories.
Clicking "Sign up" on [the dashboard](https://dashboard.stryker-mutator.io/) shows the following:

![image](https://user-images.githubusercontent.com/18365890/49421767-9fbea900-f7d4-11e8-977e-c42d3372ea86.png)
